// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-HZbwjPeYwdb-bN-IlxQ5gp61pmQG34A',
    appId: '1:421751019054:web:5d8144d5e8cd4d1b84f1bf',
    messagingSenderId: '421751019054',
    projectId: 'ecommerce-app-5239b',
    authDomain: 'ecommerce-app-5239b.firebaseapp.com',
    storageBucket: 'ecommerce-app-5239b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoMEXpdSPER5b8ld8_9XebLWDCSp_cKBg',
    appId: '1:421751019054:android:5cc030a98a1c913d84f1bf',
    messagingSenderId: '421751019054',
    projectId: 'ecommerce-app-5239b',
    storageBucket: 'ecommerce-app-5239b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZF0szCHwbt8xrhk4c0EStvolsjyswQj4',
    appId: '1:421751019054:ios:03daa54a0127eed384f1bf',
    messagingSenderId: '421751019054',
    projectId: 'ecommerce-app-5239b',
    storageBucket: 'ecommerce-app-5239b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
